---
apiVersion: v1
kind: Namespace
metadata:
   name: mynamespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mynamespace-quota
  namespace: mynamespace
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "20"
    limits.memory: 20Gi
    pods: "6"
    count/deployments.extensions: "2"
    count/services: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
  namespace: mynamespace
spec:
  limits:
  - default:
      cpu: "300m"
      memory: "500Mi"
    defaultRequest:
      cpu: "300m"
      memory: "300Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "300m"
      memory: "200Mi"
    type: Container